# Generated by Django 5.2.6 on 2025-09-22 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of your role or achievements.'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(help_text='Percentage from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='color_class',
            field=models.CharField(blank=True, help_text="e.g., 'text-blue-500' for Tailwind CSS", max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
