# Generated by Django 5.2.6 on 2025-09-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_experience_description_alter_experience_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='color_class',
        ),
        migrations.AddField(
            model_name='tool',
            name='color',
            field=models.CharField(blank=True, help_text="The hex color code for the icon, e.g., '#4B8BBE'", max_length=20),
        ),
    ]
