# Generated by Django 5.2.6 on 2025-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tool_color_class_tool_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_description',
            field=models.TextField(blank=True, help_text='Text for the contact section.'),
        ),
    ]
