# Generated by Django 5.2.6 on 2025-09-23 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_contact_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='icon',
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Upload an icon for the tool.', upload_to='tool_icons/'),
            preserve_default=False,
        ),
    ]
