# Generated by Django 5.2.6 on 2025-09-23 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_tool_color_remove_tool_icon_tool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.FileField(help_text='Upload an icon for the tool (SVG, PNG, JPG, etc.).', upload_to='tool_icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
