# Generated by Django 5.2.6 on 2025-09-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
